[32m2024-02-08 14:12:14 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f99c5afc-affb-4528-a9ba-c7afc6b746ed - 106193 - LOGS_CAPTURED - Started capturing logs in process (pid: 106193).
[32m2024-02-08 14:12:14 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f99c5afc-affb-4528-a9ba-c7afc6b746ed - 106193 - fetch_buses_data - STEP_START - Started execution of step "fetch_buses_data".
[32m2024-02-08 14:12:14 +0100[0m - dagster - [34mINFO[0m - __ASSET_JOB - f99c5afc-affb-4528-a9ba-c7afc6b746ed - fetch_buses_data - b'    {"result":"B\\u0142\\u0119dna metoda lub parametry wywo\\u0142ania"} \n'
[32m2024-02-08 14:12:14 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - f99c5afc-affb-4528-a9ba-c7afc6b746ed - 106193 - fetch_buses_data - STEP_FAILURE - Execution of step "fetch_buses_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "fetch_buses_data"::

NotImplementedError

Stack Trace:
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/home/janek/kurs_python/zadanie_zaliczeniowe/bus-analysis/bus_analysis/assets.py", line 12, in fetch_buses_data
    return warsaw_api.request_loc_in_time(2)
  File "/home/janek/kurs_python/zadanie_zaliczeniowe/bus-analysis/bus_analysis/resources.py", line 28, in request_loc_in_time
    [buses, pd.json_normalize(data["result"], errors="coerce")],
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/pandas/io/json/_normalize.py", line 445, in json_normalize
    raise NotImplementedError
[0m
