[32m2024-02-08 15:22:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 958f51c9-ae5f-4feb-8a26-3311ecdd7f9a - 189794 - LOGS_CAPTURED - Started capturing logs in process (pid: 189794).
[32m2024-02-08 15:22:54 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 958f51c9-ae5f-4feb-8a26-3311ecdd7f9a - 189794 - fetch_stops_data - STEP_START - Started execution of step "fetch_stops_data".
[32m2024-02-08 15:22:54 +0100[0m - dagster - [34mINFO[0m - __ASSET_JOB - 958f51c9-ae5f-4feb-8a26-3311ecdd7f9a - fetch_stops_data - Pobrano dane: BÅ‚Ä™dna metoda lub parametry wywoÅ‚ania
[32m2024-02-08 15:22:54 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 958f51c9-ae5f-4feb-8a26-3311ecdd7f9a - 189794 - fetch_stops_data - STEP_FAILURE - Execution of step "fetch_stops_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "fetch_stops_data"::

AttributeError: 'function' object has no attribute 'info'

Stack Trace:
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/home/janek/miniconda3/envs/bus-analysis/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/home/janek/kurs_python/zadanie_zaliczeniowe/bus-analysis/bus_analysis/assets.py", line 24, in fetch_stops_data
    get_dagster_logger.info(result)
[0m
